### ISSUE TITLE
Contact Us to use email template

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#165]
The current Contact Us form sends me an email with an ugly json object in plain text.

Change this to a table, and switch it to use the site's default email template which was recently installed.

**Comment by kylepolich** [comment]
@glozhkovoy This is still open after all latest changes deployed.

**Comment by glozhkovoy** [comment]
Commit 0665989 should fix it. If it's fixed, let's close this issue.

**Comment by kylepolich** [comment]
@glozhkovoy I just tested against latest `dev` build and this is still not implemented.

**Comment by glozhkovoy** [comment]
I fixed small issue in warning-fix PR, can you try again?
